name: Tests

on:
  push:
    branches:
      - master
      - development

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: install
            - uses: borales/actions-yarn@v2.0.0
              with:
                cmd: run prod
      - name: Generate Key
        run: php artisan key:generate
      - name: Execute Tests
        run: vendor/bin/phpunit
